/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba.coba;

import coba.coba.MainFrm.DlgHelp;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class FrmCuaca extends javax.swing.JFrame {

    /**
     * Creates new form FrmCuaca
     */
    public FrmCuaca() {
        initComponents();
        lblAngin.setText("");
        lblLembap.setText("");
        lblMax.setText("");
        lblMin.setText("");
        lblUdara.setText("");
        lblSuhu.setText("");
        lblKota.setText("Cuaca di Kota"+"");
        JOptionPane.showMessageDialog(null, "Selamat Datang Di Aplikasi Monitoring Cuaca", "Welcome", JOptionPane.PLAIN_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cbHari = new javax.swing.JComboBox<>();
        lblKota = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblAngin = new javax.swing.JLabel();
        lblLembap = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblUdara = new javax.swing.JLabel();
        lblKapan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("kota");

        txtKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hari ini", "Besok" }));
        cbHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHariActionPerformed(evt);
            }
        });

        lblKota.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblKota.setText("MONITOR CUACA");

        lblSuhu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSuhu.setText("SUHU");

        jLabel4.setText("Suhu Maksimum");

        jLabel5.setText("Suhu Minimum");

        jLabel6.setText("Kecepatan Angin");

        jLabel7.setText("Kelembapan");

        lblMax.setText("30,0*C");

        lblMin.setText("10.0*");

        lblAngin.setText("20.0 m/s");

        lblLembap.setText("200.2 %");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coba/coba/gambar/04n.png"))); // NOI18N

        jLabel16.setText("Tekanan Udara");

        lblUdara.setText("200.2 hPa");

        lblKapan.setText("Waktu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("Broken Clouds");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Kota yang terdaftar :\n1. bandung\n2. medan\n3. surabaya");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(lblKota)
                        .addGap(66, 66, 66)
                        .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKapan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSuhu)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel15))))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel16))))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAngin)
                            .addComponent(lblLembap)
                            .addComponent(lblUdara)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMax)
                                    .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKota)
                    .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKapan, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuhu)
                    .addComponent(jLabel4)
                    .addComponent(lblMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblAngin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblUdara))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLembap)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKotaActionPerformed
        // TODO add your handling code here:
        String day = (String) cbHari.getSelectedItem();
            lblKapan.setText(day);
            
            if("Hari ini".equals(lblKapan.getText())&& "bandung".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("20.3"+(char)0x00B0+"C");
                lblMax.setText("30.0"+(char)0x00B0+"C");
                lblMin.setText("10.0"+(char)0x00B0+"C");
                lblAngin.setText("20.0"+"m/s");
                lblLembap.setText("200.2"+"%");
                lblUdara.setText("200.2"+"hPa");
                
            }else if("Besok".equals(lblKapan.getText())&& "bandung".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("18.3"+(char)0x00B0+"C");
                lblMax.setText("40.0"+(char)0x00B0+"C");
                lblMin.setText("20.0"+(char)0x00B0+"C");
                lblAngin.setText("21.0"+"m/s");
                lblLembap.setText("210.2"+"%");
                lblUdara.setText("210.2"+"hPa");
            }else if("Hari ini".equals(lblKapan.getText())&& "surabaya".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("35.3"+(char)0x00B0+"C");
                lblMax.setText("40.0"+(char)0x00B0+"C");
                lblMin.setText("24.0"+(char)0x00B0+"C");
                lblAngin.setText("25.0"+"m/s");
                lblLembap.setText("240.2"+"%");
                lblUdara.setText("240.2"+"hPa");
                
            }else if("Besok".equals(lblKapan.getText())&& "surabaya".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("32.5"+(char)0x00B0+"C");
                lblMax.setText("36.7"+(char)0x00B0+"C");
                lblMin.setText("27.0"+(char)0x00B0+"C");
                lblAngin.setText("28.0"+"m/s");
                lblLembap.setText("226.2"+"%");
                lblUdara.setText("226.2"+"hPa");
            }else if("Hari ini".equals(lblKapan.getText())&& "medan".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("26.7"+(char)0x00B0+"C");
                lblMax.setText("30.0"+(char)0x00B0+"C");
                lblMin.setText("20.0"+(char)0x00B0+"C");
                lblAngin.setText("30.0"+"m/s");
                lblLembap.setText("250.2"+"%");
                lblUdara.setText("250.2"+"hPa");
                
            }else if("Besok".equals(lblKapan.getText())&& "medan".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("27.0"+(char)0x00B0+"C");
                lblMax.setText("300.0"+(char)0x00B0+"C");
                lblMin.setText("22.0"+(char)0x00B0+"C");
                lblAngin.setText("21.0"+"m/s");
                lblLembap.setText("210.2"+"%");
                lblUdara.setText("210.2"+"hPa");
            }else{
                JOptionPane.showMessageDialog(null, "Data yang anda masukan belum tersedia", "Peringatan", JOptionPane.ERROR_MESSAGE);
            }
                
    }//GEN-LAST:event_txtKotaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi Monitoring Cuaca" + "\n Trisno" + "\n 1641811");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DlgHelp help = new DlgHelp();
        help.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cbHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHariActionPerformed
        // TODO add your handling code here:
        String day = (String) cbHari.getSelectedItem();
            lblKapan.setText(day);
            
            if("Hari ini".equals(lblKapan.getText())&& "bandung".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("20.3"+(char)0x00B0+"C");
                lblMax.setText("30.0"+(char)0x00B0+"C");
                lblMin.setText("10.0"+(char)0x00B0+"C");
                lblAngin.setText("20.0"+"m/s");
                lblLembap.setText("200.2"+"%");
                lblUdara.setText("200.2"+"hPa");
                
            }else if("Besok".equals(lblKapan.getText())&& "bandung".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("18.3"+(char)0x00B0+"C");
                lblMax.setText("40.0"+(char)0x00B0+"C");
                lblMin.setText("20.0"+(char)0x00B0+"C");
                lblAngin.setText("21.0"+"m/s");
                lblLembap.setText("210.2"+"%");
                lblUdara.setText("210.2"+"hPa");
            }else if("Hari ini".equals(lblKapan.getText())&& "surabaya".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("35.3"+(char)0x00B0+"C");
                lblMax.setText("40.0"+(char)0x00B0+"C");
                lblMin.setText("24.0"+(char)0x00B0+"C");
                lblAngin.setText("25.0"+"m/s");
                lblLembap.setText("240.2"+"%");
                lblUdara.setText("240.2"+"hPa");
                
            }else if("Besok".equals(lblKapan.getText())&& "surabaya".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("32.5"+(char)0x00B0+"C");
                lblMax.setText("36.7"+(char)0x00B0+"C");
                lblMin.setText("27.0"+(char)0x00B0+"C");
                lblAngin.setText("28.0"+"m/s");
                lblLembap.setText("226.2"+"%");
                lblUdara.setText("226.2"+"hPa");
            }else if("Hari ini".equals(lblKapan.getText())&& "medan".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("26.7"+(char)0x00B0+"C");
                lblMax.setText("30.0"+(char)0x00B0+"C");
                lblMin.setText("20.0"+(char)0x00B0+"C");
                lblAngin.setText("30.0"+"m/s");
                lblLembap.setText("250.2"+"%");
                lblUdara.setText("250.2"+"hPa");
                
            }else if("Besok".equals(lblKapan.getText())&& "medan".equals(txtKota.getText())){
                lblKota.setText(txtKota.getText());
                lblSuhu.setText("27.0"+(char)0x00B0+"C");
                lblMax.setText("300.0"+(char)0x00B0+"C");
                lblMin.setText("22.0"+(char)0x00B0+"C");
                lblAngin.setText("21.0"+"m/s");
                lblLembap.setText("210.2"+"%");
                lblUdara.setText("210.2"+"hPa");
            }else{
                JOptionPane.showMessageDialog(null, "Data yang anda masukan belum tersedia", "Peringatan", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_cbHariActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAngin;
    private javax.swing.JLabel lblKapan;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblLembap;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JLabel lblUdara;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables
}
